<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Instrux.Domain\Instrux.Domain.csproj" />
    <ProjectReference Include="..\Instrux.Infrastructure\Instrux.Infrastructure.csproj" />
  </ItemGroup>

</Project>
